---
title: "Home"
---

:::{.callout-warning}
This page is work in progress.
:::

## About the homepage

The website is designed to support researchers by providing tutorials on data processing, statistical analyses and visualizations. A more detailed overview can be found in the section [Content Overview](index-content.qmd). Most of the tutorials are based on text books or papers (these are cited at the bottom of every page: References) or originate from great web resources such as [stackoverflow](https://stackoverflow.com/), or [stats.stackexchange](https://stats.stackexchange.com/).

The website is build with [Quarto](quarto.org) and is published with [Github pages](https://pages.github.com/).

## Disclaimer

All material is licensed under the MIT License [(MIT)](https://en.wikipedia.org/wiki/MIT_License) and comes with **ABSOLUTELY NO WARRANTY**. 

:::{.callout-important collapse="false"}
The MIT License

Copyright (c) 2023

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

:::

## Bugs & Errors

Found errors or any bugs? Please send us an email [&#9993;](mailto:sven.rieger@uni-tuebingen.de) or report them directly to github.com. At every page, below the table of contents, there is link to the repository of the website. If you think your issue may important for others, please use this option. 
 
## Contribution
 
If you want to contribute, please send us an email [&#9993;](mailto:sven.rieger@uni-tuebingen.de). We will check whether or to what extent your idea(s) fit/s into objective of the website.

[Hello](google.com){border=true;}
